# default.yaml - Base hyperparameters for VQ-VAE experiments

# Data parameters
d: 256  # Ambient dimension
r: 4    # Intrinsic dimension
Ntr: 20000  # Training samples
Nval: 4000  # Validation samples

# Model parameters
K: 16  # Codebook size
beta: 0.25  # Commitment loss weight

# Training parameters
epochs: 60
batch_size: 256
learning_rate: 0.002
seed: 42

# Data generation
sigma: 0.1  # Noise level

# Model configuration
orthonormal_W: true  # Whether to project W to Stiefel manifold

# Estimator type (ste or rotation)
estimator: ste