# configs/sweeps.yaml - Experiment grids for systematic evaluation

common:
  d: 256
  r: 4
  epochs: 60
  orth: true
  seed_list: [1, 2, 3, 4, 5]
  batch_size: 256
  learning_rate: 0.002
  Ntr: 20000
  Nval: 4000

grids:
  - name: A_subspace_usage
    description: "Primary experiment comparing STE vs Rotation for subspace recovery and code usage"
    params:
      estimator: [ste, rotation]
      K: [16]
      sigma: [0.1]
      beta: [0.25]

  - name: B_codebook_size
    description: "Codebook size sensitivity analysis"
    params:
      estimator: [ste, rotation]
      K: [8, 16, 32]
      sigma: [0.1]
      beta: [0.25]

  - name: C_noise
    description: "Noise robustness evaluation"
    params:
      estimator: [ste, rotation]
      K: [16]
      sigma: [0.0, 0.1, 0.3]
      beta: [0.25]

  - name: D_commitment
    description: "Commitment loss strength analysis"
    params:
      estimator: [ste, rotation]
      K: [16]
      sigma: [0.1]
      beta: [0.0, 0.25, 0.5]

  - name: E_purist
    description: "Optional experiment without orthonormal constraint"
    params:
      estimator: [ste, rotation]
      K: [16]
      sigma: [0.1]
      beta: [0.25]
      orth: [false]  # Override common setting